import { Request, Response } from 'express';
import * as svc from './contracts.service.js';
type Req = Request<{ workspaceId: string; id?: string }>;

export const listTemplates = async (req: Req, res: Response): Promise<void> => { try { res.json(await svc.listTemplates(req.params.workspaceId)); } catch (e) { res.status(500).json({ error: 'Erreur' }); } };
export const createTemplate = async (req: Req, res: Response): Promise<void> => { try { if (!req.body.name || !req.body.content) { res.status(400).json({ error: 'name et content requis' }); return; } res.status(201).json(await svc.createTemplate(req.params.workspaceId, req.body)); } catch (e) { res.status(500).json({ error: 'Erreur' }); } };
export const updateTemplate = async (req: Req, res: Response): Promise<void> => { try { const r = await svc.updateTemplate(req.params.workspaceId, req.params.id!, req.body); if (!r) { res.status(404).json({ error: 'Template non trouve' }); return; } res.json(r); } catch (e) { res.status(500).json({ error: 'Erreur' }); } };
export const deleteTemplate = async (req: Req, res: Response): Promise<void> => { try { const ok = await svc.deleteTemplate(req.params.workspaceId, req.params.id!); if (!ok) { res.status(404).json({ error: 'Template non trouve' }); return; } res.status(204).send(); } catch (e) { res.status(500).json({ error: 'Erreur' }); } };
export const listContracts = async (req: Req, res: Response): Promise<void> => { try { res.json(await svc.listContracts(req.params.workspaceId, { status: req.query.status as string, contactId: req.query.contact_id as string, page: req.query.page ? parseInt(req.query.page as string) : 1, limit: req.query.limit ? parseInt(req.query.limit as string) : 20 })); } catch (e) { res.status(500).json({ error: 'Erreur' }); } };
export const createContract = async (req: Req, res: Response): Promise<void> => { try { if (!req.body.title || !req.body.content) { res.status(400).json({ error: 'title et content requis' }); return; } res.status(201).json(await svc.createContract(req.params.workspaceId, req.body)); } catch (e) { res.status(500).json({ error: 'Erreur' }); } };
export const getContract = async (req: Req, res: Response): Promise<void> => { try { const r = await svc.getContract(req.params.workspaceId, req.params.id!); if (!r) { res.status(404).json({ error: 'Contrat non trouve' }); return; } res.json(r); } catch (e) { res.status(500).json({ error: 'Erreur' }); } };
export const updateContract = async (req: Req, res: Response): Promise<void> => { try { const r = await svc.updateContract(req.params.workspaceId, req.params.id!, req.body); if (!r) { res.status(404).json({ error: 'Contrat non trouve' }); return; } res.json(r); } catch (e) { res.status(500).json({ error: 'Erreur' }); } };
export const deleteContract = async (req: Req, res: Response): Promise<void> => { try { const ok = await svc.deleteContract(req.params.workspaceId, req.params.id!); if (!ok) { res.status(404).json({ error: 'Contrat non trouve ou non draft' }); return; } res.status(204).send(); } catch (e) { res.status(500).json({ error: 'Erreur' }); } };
export const sendForSignature = async (req: Req, res: Response): Promise<void> => { try { if (!req.body.signer_email || !req.body.signer_name) { res.status(400).json({ error: 'signer_email et signer_name requis' }); return; } res.json(await svc.sendForSignature(req.params.workspaceId, req.params.id!, req.body.signer_email, req.body.signer_name)); } catch (e: any) { res.status(e.message?.includes('non trouve') ? 404 : 500).json({ error: e.message || 'Erreur' }); } };
export const signContract = async (req: Request, res: Response): Promise<void> => { try { const r = await svc.signContract(req.params.token || req.body.token); res.json(r); } catch (e: any) { res.status(400).json({ error: e.message || 'Erreur' }); } };
