/**
 * PSYCHO-AUDIT STYLES - CSS injection
 * ProductiveApp v5.0
 */

const PaStyles = (function() {
    'use strict';

    function inject() {
        if (document.getElementById('psycho-audit-styles')) return;

        var style = document.createElement('style');
        style.id = 'psycho-audit-styles';
        style.textContent = [
            '.psycho-audit-view { padding: 24px; max-width: 800px; margin: 0 auto; }',
            '.audit-header { text-align: center; margin-bottom: 32px; }',
            '.audit-header h1 { font-size: 28px; font-weight: 700; color: var(--primary, #8b5cf6); margin-bottom: 8px; }',
            '.audit-header .subtitle { color: var(--text-secondary, #888); font-size: 14px; }',
            '',
            '/* Questionnaire */',
            '.questionnaire { background: var(--surface, #1e1e2e); border-radius: 16px; padding: 24px; }',
            '.questionnaire h2 { font-size: 18px; margin-bottom: 8px; color: var(--text, #fff); }',
            '.questionnaire-intro { color: var(--text-secondary, #888); font-size: 13px; margin-bottom: 24px; }',
            '.axis-group { margin-bottom: 24px; padding: 20px; background: var(--surface-hover, #2a2a3e); border-radius: 14px; }',
            '.axis-header { display: flex; align-items: center; gap: 10px; margin-bottom: 16px; padding-bottom: 12px; border-bottom: 1px solid var(--border, #333); }',
            '.axis-icon { font-size: 22px; }',
            '.axis-label { color: var(--primary, #8b5cf6); font-size: 15px; font-weight: 600; }',
            '.question-item { margin-bottom: 16px; padding: 14px; background: var(--surface, #1e1e2e); border-radius: 10px; }',
            '.question-item:last-child { margin-bottom: 0; }',
            '.question-text { color: var(--text, #fff); font-size: 14px; line-height: 1.5; margin-bottom: 12px; }',
            '.question-header { display: flex; align-items: center; gap: 10px; margin-bottom: 12px; }',
            '.question-icon { font-size: 20px; }',
            '.question-label { color: var(--text, #fff); font-size: 14px; }',
            '.stars-container { display: flex; gap: 8px; justify-content: center; }',
            '.star-btn { background: none; border: none; cursor: pointer; padding: 4px; transition: transform 0.15s; }',
            '.star-btn:hover { transform: scale(1.2); }',
            '.star-btn.filled svg polygon { fill: var(--accent, #f59e0b); stroke: var(--accent, #f59e0b); }',
            '.btn-analyze { width: 100%; padding: 16px; margin-top: 24px; background: linear-gradient(135deg, var(--primary, #8b5cf6), #6366f1); color: #fff; border: none; border-radius: 12px; font-size: 16px; font-weight: 600; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: 8px; transition: transform 0.2s, opacity 0.2s; }',
            '.btn-analyze:hover:not(:disabled) { transform: translateY(-2px); }',
            '.btn-analyze:disabled { opacity: 0.5; cursor: not-allowed; }',
            '.hint { text-align: center; color: var(--text-secondary, #888); font-size: 12px; margin-top: 12px; }',
            '',
            '/* Results */',
            '.results { display: flex; flex-direction: column; gap: 24px; }',
            '.score-section { text-align: center; padding: 32px; background: var(--surface, #1e1e2e); border-radius: 16px; }',
            '.score-badge { display: inline-flex; align-items: baseline; padding: 16px 32px; border-radius: 16px; border: 2px solid; }',
            '.score-value { font-size: 48px; font-weight: 800; }',
            '.score-max { font-size: 24px; opacity: 0.6; margin-left: 4px; }',
            '.score-label { font-size: 18px; font-weight: 600; margin-top: 12px; }',
            '.score-date { color: var(--text-secondary, #888); font-size: 13px; margin-top: 8px; }',
            '.xp-badge { display: inline-block; margin-top: 12px; padding: 6px 12px; background: var(--accent, #f59e0b); color: #000; border-radius: 20px; font-size: 12px; font-weight: 700; }',
            '',
            '/* Radar */',
            '.radar-section { background: var(--surface, #1e1e2e); border-radius: 16px; padding: 24px; text-align: center; }',
            '.radar-section h3 { font-size: 16px; margin-bottom: 16px; color: var(--text, #fff); }',
            '.radar-container { display: flex; justify-content: center; }',
            '',
            '/* Recommendations */',
            '.recommendations-section { background: var(--surface, #1e1e2e); border-radius: 16px; padding: 24px; }',
            '.recommendations-section h3 { font-size: 16px; margin-bottom: 16px; color: var(--text, #fff); }',
            '.recommendation-item { display: flex; gap: 12px; padding: 14px; background: var(--surface-hover, #2a2a3e); border-radius: 10px; margin-bottom: 10px; }',
            '.rec-icon { font-size: 20px; }',
            '.rec-area { font-size: 12px; color: var(--text-secondary, #888); margin-bottom: 4px; }',
            '.rec-text { color: var(--text, #fff); font-size: 14px; }',
            '',
            '/* Trends */',
            '.trends-section { background: var(--surface, #1e1e2e); border-radius: 16px; padding: 24px; }',
            '.trends-section h3 { font-size: 16px; margin-bottom: 16px; color: var(--text, #fff); }',
            '.trends-chart { height: 120px; margin-bottom: 12px; }',
            '.trends-svg, .evolution-svg { width: 100%; height: 100%; }',
            '.trends-empty, .chart-empty { color: var(--text-secondary, #888); font-size: 13px; text-align: center; padding: 24px; }',
            '.trends-comparison { text-align: center; font-size: 14px; color: var(--text-secondary, #888); }',
            '.trends-diff { font-weight: 700; }',
            '',
            '/* History */',
            '.history-section { background: var(--surface, #1e1e2e); border-radius: 16px; padding: 24px; }',
            '.history-section h3 { font-size: 16px; margin-bottom: 16px; color: var(--text, #fff); }',
            '.history-item { display: flex; align-items: center; gap: 12px; padding: 10px 0; border-bottom: 1px solid var(--border, #333); }',
            '.history-item:last-child { border-bottom: none; }',
            '.history-date { font-size: 13px; color: var(--text-secondary, #888); width: 80px; }',
            '.history-bar { flex: 1; height: 8px; background: var(--surface-hover, #2a2a3e); border-radius: 4px; overflow: hidden; }',
            '.history-fill { height: 100%; border-radius: 4px; transition: width 0.3s; }',
            '.history-score { font-size: 14px; font-weight: 700; width: 40px; text-align: right; }',
            '',
            '/* New Audit Button */',
            '.btn-new-audit { width: 100%; padding: 14px; background: var(--surface, #1e1e2e); color: var(--text, #fff); border: 2px solid var(--border, #333); border-radius: 12px; font-size: 15px; font-weight: 500; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: 8px; transition: all 0.2s; }',
            '.btn-new-audit:hover { border-color: var(--primary, #8b5cf6); background: var(--surface-hover, #2a2a3e); }',
            '',
            '/* AI Report */',
            '.ai-report-section { background: var(--surface, #1e1e2e); border-radius: 16px; padding: 24px; }',
            '.ai-report-section h3 { font-size: 16px; margin-bottom: 16px; color: var(--text, #fff); }',
            '.pa-report-btn { width: 100%; padding: 14px; background: linear-gradient(135deg, #10b981, #059669); color: #fff; border: none; border-radius: 12px; font-size: 15px; font-weight: 600; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: 8px; transition: all 0.2s; }',
            '.pa-report-btn:hover { transform: translateY(-2px); box-shadow: 0 4px 12px rgba(16,185,129,0.3); }',
            '.pa-report-container { margin-top: 16px; }',
            '.pa-report-loading { text-align: center; padding: 32px; color: var(--text-secondary, #888); }',
            '.pa-report-loading .loading-spinner { width: 32px; height: 32px; border: 3px solid var(--border, #333); border-top-color: var(--accent, #f59e0b); border-radius: 50%; animation: spin 1s linear infinite; margin: 0 auto 12px; }',
            '@keyframes spin { to { transform: rotate(360deg); } }',
            '.pa-report-content { background: var(--surface-hover, #2a2a3e); border-radius: 12px; padding: 20px; color: var(--text, #fff); font-size: 14px; line-height: 1.6; }',
            '.pa-report-content h3 { font-size: 18px; color: var(--primary, #8b5cf6); margin: 16px 0 8px; }',
            '.pa-report-content h4 { font-size: 15px; color: var(--accent, #f59e0b); margin: 12px 0 6px; }',
            '.pa-report-content ul { margin: 8px 0; padding-left: 20px; }',
            '.pa-report-content li { margin: 4px 0; }',
            '.pa-report-content pre { background: var(--surface, #1e1e2e); padding: 12px; border-radius: 8px; font-size: 12px; overflow-x: auto; }',
            '.pa-report-table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 13px; }',
            '.pa-report-table td { padding: 8px; border: 1px solid var(--border, #333); }',
            '.pa-report-content hr { border: none; border-top: 1px solid var(--border, #333); margin: 16px 0; }',
            '.pa-report-empty { text-align: center; color: var(--text-secondary, #888); padding: 24px; }',
            '',
            '@media (max-width: 600px) {',
            '    .psycho-audit-view { padding: 16px; }',
            '    .audit-header h1 { font-size: 22px; }',
            '    .score-value { font-size: 36px; }',
            '}',
            '',
            '/* ============================================================ */',
            '/* PREMIUM UI v6.0 - Styles for multi-tab therapeutic experience */',
            '/* ============================================================ */',
            '',
            '/* Premium Wrapper */',
            '.pa-premium-wrapper { max-width: 900px; margin: 0 auto; padding: 20px; }',
            '',
            '/* Premium Header */',
            '.pa-premium-header { text-align: center; margin-bottom: 24px; padding: 24px 0 16px; }',
            '.pa-premium-title-row { display: flex; align-items: center; justify-content: center; gap: 12px; }',
            '.pa-premium-title { font-size: 28px; font-weight: 800; color: var(--text, #fff); margin: 0; }',
            '.pa-premium-badge { background: linear-gradient(135deg, #d946ef, #8b5cf6); color: #fff; font-size: 11px; font-weight: 700; padding: 4px 10px; border-radius: 20px; text-transform: uppercase; letter-spacing: 0.5px; }',
            '.pa-premium-subtitle { color: var(--text-secondary, #888); font-size: 13px; margin-top: 8px; }',
            '',
            '/* Tab Bar */',
            '.pa-premium-tabs { display: flex; gap: 4px; background: var(--surface, #1e1e2e); border-radius: 14px; padding: 4px; margin-bottom: 24px; overflow-x: auto; }',
            '.pa-tab-btn { flex: 1; display: flex; align-items: center; justify-content: center; gap: 6px; padding: 12px 8px; border: none; background: transparent; color: var(--text-secondary, #888); font-size: 13px; font-weight: 500; border-radius: 10px; cursor: pointer; transition: all 0.2s; white-space: nowrap; }',
            '.pa-tab-btn:hover { color: var(--text, #fff); background: var(--surface-hover, #2a2a3e); }',
            '.pa-tab-btn.active { background: var(--primary, #8b5cf6); color: #fff; font-weight: 600; }',
            '.pa-tab-icon { font-size: 16px; }',
            '.pa-tab-label { font-size: 12px; }',
            '',
            '/* Premium Content */',
            '.pa-premium-content { min-height: 400px; }',
            '',
            '/* Section Titles */',
            '.pa-section-title { font-size: 16px; font-weight: 600; color: var(--text, #fff); margin-bottom: 16px; display: flex; align-items: center; gap: 8px; }',
            '.pa-section-icon { font-size: 18px; }',
            '.pa-section-desc { color: var(--text-secondary, #888); font-size: 13px; margin-bottom: 16px; }',
            '',
            '/* Back Button */',
            '.pa-back-btn { background: none; border: none; color: var(--primary, #8b5cf6); font-size: 14px; cursor: pointer; padding: 8px 0; margin-bottom: 16px; display: flex; align-items: center; gap: 4px; }',
            '.pa-back-btn:hover { color: var(--accent, #f59e0b); }',
            '',
            '/* Primary & Secondary Buttons */',
            '.pa-btn-primary { width: 100%; padding: 14px 24px; background: linear-gradient(135deg, var(--primary, #8b5cf6), #6366f1); color: #fff; border: none; border-radius: 12px; font-size: 15px; font-weight: 600; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: 8px; transition: all 0.2s; }',
            '.pa-btn-primary:hover { transform: translateY(-2px); box-shadow: 0 4px 16px rgba(139,92,246,0.3); }',
            '.pa-btn-secondary { padding: 12px 20px; background: var(--surface, #1e1e2e); color: var(--text, #fff); border: 1px solid var(--border, #333); border-radius: 10px; font-size: 14px; cursor: pointer; transition: all 0.2s; }',
            '.pa-btn-secondary:hover { border-color: var(--primary, #8b5cf6); }',
            '',
            '/* =================== */',
            '/* Exercise Cards */',
            '/* =================== */',
            '.pa-exercise-cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 16px; margin-bottom: 24px; }',
            '.pa-exercise-card { background: var(--surface, #1e1e2e); border-radius: 14px; overflow: hidden; cursor: pointer; transition: all 0.2s; border: 1px solid var(--border, #333); position: relative; }',
            '.pa-exercise-card:hover { transform: translateY(-3px); box-shadow: 0 8px 24px rgba(0,0,0,0.2); border-color: var(--primary, #8b5cf6); }',
            '.pa-exercise-card.urgent { border-color: #ef4444; }',
            '.pa-ex-card-accent { height: 4px; width: 100%; }',
            '.pa-ex-card-body { padding: 16px; }',
            '.pa-ex-card-top { display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px; }',
            '.pa-ex-card-diff { font-size: 11px; font-weight: 600; padding: 3px 8px; border-radius: 6px; }',
            '.pa-ex-card-duration { font-size: 12px; color: var(--text-secondary, #888); }',
            '.pa-ex-card-title { font-size: 15px; font-weight: 600; color: var(--text, #fff); margin-bottom: 6px; line-height: 1.3; }',
            '.pa-ex-card-subtitle { font-size: 12px; color: var(--text-secondary, #888); margin-bottom: 10px; line-height: 1.4; }',
            '.pa-ex-card-evidence { display: flex; align-items: center; gap: 8px; }',
            '.pa-evidence-badge { font-size: 10px; font-weight: 700; background: rgba(34,197,94,0.15); color: #22c55e; padding: 2px 8px; border-radius: 4px; }',
            '.pa-evidence-by { font-size: 10px; color: var(--text-secondary, #666); }',
            '',
            '/* =================== */',
            '/* Exercise Detail */',
            '/* =================== */',
            '.pa-exercise-detail { animation: fadeInUp 0.3s ease; }',
            '.pa-ex-detail-header { text-align: center; padding: 24px; background: var(--surface, #1e1e2e); border-radius: 16px; margin-bottom: 20px; }',
            '.pa-ex-detail-header h2 { font-size: 24px; font-weight: 700; color: var(--text, #fff); margin-bottom: 8px; }',
            '.pa-ex-detail-subtitle { color: var(--text-secondary, #888); font-size: 13px; margin-bottom: 16px; }',
            '.pa-ex-detail-meta { display: flex; justify-content: center; gap: 16px; flex-wrap: wrap; }',
            '.pa-meta-item { font-size: 13px; color: var(--text-secondary, #888); }',
            '',
            '/* Evidence Box */',
            '.pa-ex-evidence-box { background: linear-gradient(135deg, rgba(34,197,94,0.08), rgba(34,197,94,0.03)); border: 1px solid rgba(34,197,94,0.2); border-radius: 14px; padding: 20px; margin-bottom: 20px; }',
            '.pa-evidence-header { display: flex; align-items: center; gap: 10px; margin-bottom: 12px; }',
            '.pa-evidence-icon { font-size: 20px; }',
            '.pa-evidence-header h3 { font-size: 15px; font-weight: 600; color: #22c55e; margin: 0; }',
            '.pa-evidence-text { color: var(--text, #fff); font-size: 13px; line-height: 1.7; margin-bottom: 12px; }',
            '.pa-evidence-footer { display: flex; align-items: center; gap: 12px; }',
            '.pa-evidence-org { font-size: 12px; color: var(--text-secondary, #888); }',
            '',
            '/* Description */',
            '.pa-ex-description { background: var(--surface, #1e1e2e); border-radius: 14px; padding: 20px; margin-bottom: 20px; }',
            '.pa-ex-description p { color: var(--text, #fff); font-size: 14px; line-height: 1.7; }',
            '',
            '/* Steps */',
            '.pa-ex-steps { margin-bottom: 20px; }',
            '.pa-ex-steps h3 { font-size: 16px; font-weight: 600; color: var(--text, #fff); margin-bottom: 16px; }',
            '.pa-step-card { display: flex; gap: 16px; padding: 16px; background: var(--surface, #1e1e2e); border-radius: 12px; margin-bottom: 12px; border-left: 3px solid var(--primary, #8b5cf6); }',
            '.pa-step-number { width: 36px; height: 36px; min-width: 36px; background: var(--primary, #8b5cf6); color: #fff; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 14px; }',
            '.pa-step-body { flex: 1; }',
            '.pa-step-top { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }',
            '.pa-step-top h4 { font-size: 14px; font-weight: 600; color: var(--primary, #8b5cf6); margin: 0; }',
            '.pa-step-dur { font-size: 12px; color: var(--text-secondary, #888); background: var(--surface-hover, #2a2a3e); padding: 2px 8px; border-radius: 6px; }',
            '.pa-step-body p { color: var(--text, #fff); font-size: 13px; line-height: 1.6; margin: 0; }',
            '',
            '/* Results & Testimonial */',
            '.pa-ex-results { background: linear-gradient(135deg, rgba(139,92,246,0.08), rgba(99,102,241,0.04)); border: 1px solid rgba(139,92,246,0.2); border-radius: 14px; padding: 20px; margin-bottom: 20px; }',
            '.pa-results-header { display: flex; align-items: center; gap: 10px; margin-bottom: 12px; }',
            '.pa-results-icon { font-size: 20px; }',
            '.pa-results-header h3 { font-size: 15px; font-weight: 600; color: var(--primary, #8b5cf6); margin: 0; }',
            '.pa-ex-results p { color: var(--text, #fff); font-size: 13px; line-height: 1.7; }',
            '',
            '.pa-ex-testimonial { background: var(--surface, #1e1e2e); border-radius: 14px; padding: 20px; margin-bottom: 20px; border-left: 4px solid var(--accent, #f59e0b); }',
            '.pa-testimonial-icon { font-size: 24px; margin-bottom: 8px; }',
            '.pa-ex-testimonial blockquote { color: var(--text, #fff); font-size: 13px; line-height: 1.7; font-style: italic; margin: 0; }',
            '',
            '.pa-ex-contra { background: rgba(239,68,68,0.08); border: 1px solid rgba(239,68,68,0.2); border-radius: 12px; padding: 16px; margin-bottom: 20px; display: flex; gap: 12px; align-items: flex-start; }',
            '.pa-contra-icon { font-size: 20px; }',
            '.pa-ex-contra p { color: #ef4444; font-size: 13px; line-height: 1.5; margin: 0; }',
            '',
            '/* Exercise Actions */',
            '.pa-ex-actions { display: flex; gap: 12px; margin-bottom: 24px; }',
            '.pa-btn-start { flex: 2; }',
            '',
            '/* =================== */',
            '/* Guided Exercise */',
            '/* =================== */',
            '.pa-guided-step { text-align: center; padding: 32px; background: var(--surface, #1e1e2e); border-radius: 16px; }',
            '.pa-guided-progress { height: 4px; background: var(--surface-hover, #2a2a3e); border-radius: 2px; margin-bottom: 24px; overflow: hidden; }',
            '.pa-guided-fill { height: 100%; background: linear-gradient(90deg, var(--primary, #8b5cf6), #d946ef); border-radius: 2px; transition: width 0.4s; }',
            '.pa-guided-step-num { font-size: 12px; color: var(--text-secondary, #888); margin-bottom: 8px; }',
            '.pa-guided-title { font-size: 22px; font-weight: 700; color: var(--primary, #8b5cf6); margin-bottom: 16px; }',
            '.pa-guided-instruction { color: var(--text, #fff); font-size: 16px; line-height: 1.8; max-width: 600px; margin: 0 auto 24px; }',
            '.pa-guided-timer { font-size: 48px; font-weight: 800; color: var(--accent, #f59e0b); margin-bottom: 24px; font-variant-numeric: tabular-nums; }',
            '.pa-guided-btns { display: flex; gap: 12px; justify-content: center; }',
            '.pa-guided-complete { text-align: center; padding: 48px; }',
            '.pa-complete-icon { font-size: 48px; margin-bottom: 16px; }',
            '',
            '/* =================== */',
            '/* Therapy Tab */',
            '/* =================== */',
            '.pa-therapy-tab { }',
            '.pa-therapy-header { text-align: center; margin-bottom: 24px; }',
            '.pa-therapy-header h2 { font-size: 20px; font-weight: 700; color: var(--text, #fff); margin-bottom: 8px; }',
            '.pa-therapy-header p { color: var(--text-secondary, #888); font-size: 13px; }',
            '.pa-therapy-section { margin-bottom: 28px; }',
            '.pa-therapy-empty { text-align: center; padding: 60px 24px; }',
            '.pa-empty-icon { font-size: 48px; margin-bottom: 16px; }',
            '.pa-therapy-empty h3 { font-size: 18px; color: var(--text, #fff); margin-bottom: 8px; }',
            '.pa-therapy-empty p { color: var(--text-secondary, #888); font-size: 14px; max-width: 400px; margin: 0 auto 20px; }',
            '',
            '/* Daily Routine */',
            '.pa-daily-routine { display: flex; flex-direction: column; gap: 8px; }',
            '.pa-daily-slot { display: flex; align-items: center; gap: 16px; padding: 16px; background: var(--surface, #1e1e2e); border-radius: 12px; cursor: pointer; transition: all 0.2s; border: 1px solid var(--border, #333); }',
            '.pa-daily-slot:hover { border-color: var(--primary, #8b5cf6); transform: translateX(4px); }',
            '.pa-daily-time { font-size: 12px; font-weight: 600; color: var(--accent, #f59e0b); min-width: 120px; }',
            '.pa-daily-info { flex: 1; }',
            '.pa-daily-name { font-size: 14px; font-weight: 600; color: var(--text, #fff); margin-bottom: 2px; }',
            '.pa-daily-reason { font-size: 12px; color: var(--text-secondary, #888); }',
            '.pa-daily-arrow { font-size: 18px; color: var(--primary, #8b5cf6); }',
            '',
            '/* =================== */',
            '/* Library Tab */',
            '/* =================== */',
            '.pa-library-tab { }',
            '.pa-library-header { text-align: center; margin-bottom: 20px; }',
            '.pa-library-header h2 { font-size: 20px; font-weight: 700; color: var(--text, #fff); margin-bottom: 8px; }',
            '.pa-library-header p { color: var(--text-secondary, #888); font-size: 13px; }',
            '',
            '/* Filter Bar */',
            '.pa-filter-bar { display: flex; gap: 6px; flex-wrap: wrap; margin-bottom: 24px; padding: 8px; background: var(--surface, #1e1e2e); border-radius: 12px; }',
            '.pa-filter-btn { padding: 8px 12px; border: none; background: transparent; color: var(--text-secondary, #888); font-size: 12px; border-radius: 8px; cursor: pointer; transition: all 0.15s; display: flex; align-items: center; gap: 4px; white-space: nowrap; }',
            '.pa-filter-btn:hover { color: var(--text, #fff); background: var(--surface-hover, #2a2a3e); }',
            '.pa-filter-btn.active { background: var(--primary, #8b5cf6); color: #fff; font-weight: 600; }',
            '',
            '/* Category Section */',
            '.pa-category-section { margin-bottom: 28px; }',
            '.pa-category-header { display: flex; align-items: flex-start; gap: 14px; padding: 16px; margin-bottom: 16px; border-radius: 12px; background: var(--surface, #1e1e2e); }',
            '.pa-category-icon { font-size: 28px; }',
            '.pa-category-info h3 { font-size: 16px; font-weight: 600; color: var(--text, #fff); margin: 0 0 4px; }',
            '.pa-category-info p { font-size: 12px; color: var(--text-secondary, #888); margin: 0; line-height: 1.4; }',
            '',
            '/* =================== */',
            '/* Programs Tab */',
            '/* =================== */',
            '.pa-programs-tab { }',
            '.pa-programs-header { text-align: center; margin-bottom: 24px; }',
            '.pa-programs-header h2 { font-size: 20px; font-weight: 700; color: var(--text, #fff); margin-bottom: 8px; }',
            '.pa-programs-header p { color: var(--text-secondary, #888); font-size: 13px; max-width: 500px; margin: 0 auto; }',
            '',
            '.pa-program-card { background: var(--surface, #1e1e2e); border-radius: 16px; padding: 20px; margin-bottom: 16px; cursor: pointer; transition: all 0.2s; border: 1px solid var(--border, #333); }',
            '.pa-program-card:hover { transform: translateY(-3px); box-shadow: 0 8px 24px rgba(0,0,0,0.2); border-color: var(--primary, #8b5cf6); }',
            '.pa-program-card.recommended { border-color: var(--accent, #f59e0b); }',
            '.pa-program-rec-badge { font-size: 11px; font-weight: 700; color: var(--accent, #f59e0b); text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 12px; }',
            '.pa-program-card-header { display: flex; align-items: center; gap: 14px; margin-bottom: 12px; }',
            '.pa-program-card-icon { font-size: 36px; }',
            '.pa-program-card-info h3 { font-size: 18px; font-weight: 700; color: var(--text, #fff); margin: 0 0 4px; }',
            '.pa-program-card-subtitle { font-size: 12px; color: var(--text-secondary, #888); margin: 0; }',
            '.pa-program-card-desc { font-size: 13px; color: var(--text, #fff); line-height: 1.6; margin-bottom: 12px; }',
            '.pa-program-card-meta { display: flex; gap: 16px; }',
            '',
            '/* Program Detail */',
            '.pa-program-detail { animation: fadeInUp 0.3s ease; }',
            '.pa-program-detail-header { text-align: center; padding: 24px; background: var(--surface, #1e1e2e); border-radius: 16px; margin-bottom: 24px; }',
            '.pa-program-detail-icon { font-size: 48px; margin-bottom: 12px; }',
            '.pa-program-detail-header h2 { font-size: 24px; font-weight: 700; color: var(--text, #fff); margin: 0 0 8px; }',
            '.pa-program-detail-subtitle { font-size: 14px; color: var(--primary, #8b5cf6); margin-bottom: 12px; }',
            '.pa-program-detail-desc { font-size: 13px; color: var(--text-secondary, #888); max-width: 500px; margin: 0 auto; line-height: 1.6; }',
            '',
            '/* Week Cards */',
            '.pa-program-timeline { display: flex; flex-direction: column; gap: 12px; }',
            '.pa-week-card { background: var(--surface, #1e1e2e); border-radius: 12px; padding: 16px; border: 1px solid var(--border, #333); }',
            '.pa-week-header { display: flex; align-items: center; gap: 12px; margin-bottom: 12px; }',
            '.pa-week-number { background: var(--primary, #8b5cf6); color: #fff; font-size: 12px; font-weight: 700; padding: 4px 10px; border-radius: 8px; }',
            '.pa-week-theme { font-size: 15px; font-weight: 600; color: var(--text, #fff); }',
            '.pa-week-exercises { display: flex; flex-direction: column; gap: 6px; }',
            '.pa-week-exercise { display: flex; justify-content: space-between; align-items: center; padding: 10px 12px; background: var(--surface-hover, #2a2a3e); border-radius: 8px; cursor: pointer; transition: all 0.15s; }',
            '.pa-week-exercise:hover { background: var(--primary, #8b5cf6); }',
            '.pa-week-exercise:hover .pa-week-ex-title, .pa-week-exercise:hover .pa-week-ex-dur { color: #fff; }',
            '.pa-week-ex-title { font-size: 13px; color: var(--text, #fff); }',
            '.pa-week-ex-dur { font-size: 11px; color: var(--text-secondary, #888); }',
            '',
            '/* =================== */',
            '/* Journal Tab */',
            '/* =================== */',
            '.pa-journal-tab { }',
            '.pa-journal-header { text-align: center; margin-bottom: 24px; }',
            '.pa-journal-header h2 { font-size: 20px; font-weight: 700; color: var(--text, #fff); margin-bottom: 8px; }',
            '.pa-journal-header p { color: var(--text-secondary, #888); font-size: 13px; }',
            '',
            '/* Mood Buttons */',
            '.pa-journal-mood { background: var(--surface, #1e1e2e); border-radius: 16px; padding: 24px; margin-bottom: 20px; text-align: center; }',
            '.pa-journal-mood h3 { font-size: 16px; color: var(--text, #fff); margin-bottom: 16px; }',
            '.pa-mood-buttons { display: flex; gap: 12px; justify-content: center; }',
            '.pa-mood-btn { display: flex; flex-direction: column; align-items: center; gap: 6px; padding: 14px 16px; background: var(--surface-hover, #2a2a3e); border: 2px solid transparent; border-radius: 12px; cursor: pointer; transition: all 0.2s; }',
            '.pa-mood-btn:hover { border-color: var(--primary, #8b5cf6); transform: translateY(-3px); }',
            '.pa-mood-emoji { font-size: 28px; }',
            '.pa-mood-label { font-size: 11px; color: var(--text-secondary, #888); }',
            '',
            '/* Journal Prompts */',
            '.pa-journal-prompts { background: var(--surface, #1e1e2e); border-radius: 16px; padding: 24px; margin-bottom: 20px; }',
            '.pa-journal-prompts h3 { font-size: 16px; color: var(--text, #fff); margin-bottom: 16px; }',
            '.pa-prompts-list { display: flex; flex-direction: column; gap: 16px; margin-bottom: 16px; }',
            '.pa-prompt-card { background: var(--surface-hover, #2a2a3e); border-radius: 12px; padding: 16px; }',
            '.pa-prompt-icon { font-size: 20px; margin-bottom: 8px; }',
            '.pa-prompt-text { font-size: 14px; color: var(--text, #fff); margin-bottom: 10px; font-weight: 500; }',
            '.pa-prompt-input { width: 100%; background: var(--surface, #1e1e2e); border: 1px solid var(--border, #333); border-radius: 8px; padding: 10px 12px; color: var(--text, #fff); font-size: 13px; resize: vertical; font-family: inherit; box-sizing: border-box; }',
            '.pa-prompt-input:focus { outline: none; border-color: var(--primary, #8b5cf6); }',
            '',
            '/* Gratitude Section */',
            '.pa-journal-gratitude { background: var(--surface, #1e1e2e); border-radius: 16px; padding: 24px; margin-bottom: 20px; }',
            '.pa-journal-gratitude h3 { font-size: 16px; color: var(--text, #fff); margin-bottom: 8px; }',
            '.pa-journal-gratitude-desc { font-size: 12px; color: var(--text-secondary, #888); margin-bottom: 16px; line-height: 1.5; }',
            '.pa-gratitude-inputs { display: flex; flex-direction: column; gap: 10px; }',
            '.pa-gratitude-row { display: flex; align-items: center; gap: 12px; }',
            '.pa-gratitude-num { width: 28px; height: 28px; min-width: 28px; background: var(--accent, #f59e0b); color: #000; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 13px; }',
            '.pa-gratitude-input { flex: 1; background: var(--surface-hover, #2a2a3e); border: 1px solid var(--border, #333); border-radius: 8px; padding: 10px 12px; color: var(--text, #fff); font-size: 13px; font-family: inherit; }',
            '.pa-gratitude-input:focus { outline: none; border-color: var(--accent, #f59e0b); }',
            '',
            '/* Exercise Tracker */',
            '.pa-journal-tracker { background: var(--surface, #1e1e2e); border-radius: 16px; padding: 24px; margin-bottom: 20px; }',
            '.pa-journal-tracker h3 { font-size: 16px; color: var(--text, #fff); margin-bottom: 16px; }',
            '.pa-tracker-list { display: flex; flex-direction: column; gap: 8px; }',
            '.pa-tracker-item { display: flex; align-items: center; gap: 12px; padding: 10px; background: var(--surface-hover, #2a2a3e); border-radius: 8px; }',
            '.pa-tracker-check { color: #22c55e; font-weight: 700; }',
            '.pa-tracker-name { flex: 1; font-size: 13px; color: var(--text, #fff); }',
            '.pa-tracker-time { font-size: 12px; color: var(--text-secondary, #888); }',
            '.pa-tracker-empty { font-size: 13px; color: var(--text-secondary, #888); }',
            '',
            '/* =================== */',
            '/* Recommended Section (in results) */',
            '/* =================== */',
            '.pa-recommended-section { background: var(--surface, #1e1e2e); border-radius: 16px; padding: 24px; }',
            '.pa-program-suggestion { margin-top: 20px; }',
            '.pa-program-suggestion-inner { display: flex; align-items: center; gap: 16px; padding: 20px; background: linear-gradient(135deg, rgba(217,70,239,0.08), rgba(139,92,246,0.08)); border: 1px solid rgba(217,70,239,0.2); border-radius: 14px; }',
            '.pa-program-icon { font-size: 36px; }',
            '.pa-program-info { flex: 1; }',
            '.pa-program-info h4 { font-size: 15px; font-weight: 600; color: var(--text, #fff); margin: 0 0 4px; }',
            '.pa-program-info p { font-size: 12px; color: var(--text-secondary, #888); margin: 0; line-height: 1.4; }',
            '.pa-btn-program { padding: 10px 16px; background: var(--primary, #8b5cf6); color: #fff; border: none; border-radius: 8px; font-size: 13px; font-weight: 600; cursor: pointer; white-space: nowrap; }',
            '.pa-btn-program:hover { background: #7c3aed; }',
            '',
            '/* Animations */',
            '@keyframes fadeInUp { from { opacity: 0; transform: translateY(16px); } to { opacity: 1; transform: translateY(0); } }',
            '',
            '/* Mobile */',
            '@media (max-width: 600px) {',
            '  .pa-premium-wrapper { padding: 12px; }',
            '  .pa-premium-title { font-size: 22px; }',
            '  .pa-tab-label { display: none; }',
            '  .pa-tab-btn { padding: 10px; }',
            '  .pa-exercise-cards { grid-template-columns: 1fr; }',
            '  .pa-mood-buttons { flex-wrap: wrap; }',
            '  .pa-program-suggestion-inner { flex-direction: column; text-align: center; }',
            '  .pa-ex-actions { flex-direction: column; }',
            '  .pa-daily-slot { flex-direction: column; align-items: flex-start; gap: 8px; }',
            '  .pa-filter-bar { flex-wrap: nowrap; overflow-x: auto; }',
            '}'
        ].join('\n');

        document.head.appendChild(style);
    }

    return { inject: inject };
})();

if (typeof window !== 'undefined') {
    window.PaStyles = PaStyles;
}
