import { Router } from 'express';
import * as ctrl from './relances.controller.js';
const router = Router({ mergeParams: true });
router.get('/settings', ctrl.getSettings);
router.put('/settings', ctrl.updateSettings);
router.post('/schedule', ctrl.schedule);
router.post('/process', ctrl.process);
router.get('/reminders', ctrl.list);
router.post('/reminders/:id/cancel', ctrl.cancel);
router.get('/overdue', ctrl.overdueReport);
export default router;
